<a href="https://colab.research.google.com/github/AlexMattyou/AI/blob/main/Try-outs/Random-forest(USsalary).ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

train = pd.read_csv('https://data.alexmattyou.repl.co/db/US-salary/train.csv')
test = pd.read_csv('https://data.alexmattyou.repl.co/db/US-salary/test.csv')

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  31978 non-null  object
 14  target          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [3]:
print ("The train data has",train.shape)
print ("The test data has",test.shape)

The train data has (32561, 15)
The test data has (16281, 15)

In [4]:
train.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
train.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
target               0
dtype: int64

In [6]:
train.workclass.fillna('Private',inplace=True)
train.occupation.fillna('Prof-specialty',inplace=True)
train['native.country'].fillna('United-States',inplace=True)

In [7]:
(train.target.value_counts()/train.shape[0])*100

 <=50K    75.919044
 >50K     24.080956
Name: target, dtype: float64

In [15]:
(pd.crosstab(train.education, train.target,margins=True)/train.shape[0])*100

target             <=50K       >50K         All
education
 10th           2.674979   0.190412    2.865391
 11th           3.424342   0.184270    3.608612
 12th           1.228463   0.101348    1.329812
 1st-4th        0.497528   0.018427    0.515955
 5th-6th        0.973557   0.049139    1.022696
 7th-8th        1.861122   0.122846    1.983969
 9th            1.495654   0.082921    1.578576
 Assoc-acdm     2.463069   0.813857    3.276926
 Assoc-voc      3.135653   1.108688    4.244341
 Bachelors      9.625012   6.821044   16.446055
 Doctorate      0.328614   0.939775    1.268389
 HS-grad       27.106047   5.144191   32.250238
 Masters        2.346365   2.945241    5.291607
 Preschool      0.156629   0.000000    0.156629
 Prof-school    0.469887   1.299100    1.768987
 Some-college  18.132121   4.259697   22.391818
All            75.919044  24.080956  100.000000

In [16]:
from sklearn import preprocessing

for x in train.columns:
    if train[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train[x].values))
        train[x] = lbl.transform(list(train[x].values))

In [19]:
train.head(100)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,target
0,39,6,77516,9,13,4,0,1,4,1,2174,0,40,38,0
1,50,5,83311,9,13,2,3,0,4,1,0,0,13,38,0
2,38,3,215646,11,9,0,5,1,4,1,0,0,40,38,0
3,53,3,234721,1,7,2,5,0,2,1,0,0,40,38,0
4,28,3,338409,9,13,2,9,5,2,0,0,0,40,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,29,1,115585,15,10,4,5,1,4,1,0,0,50,38,0
96,48,5,191277,10,16,2,9,0,4,1,0,1902,60,38,1
97,37,3,202683,15,10,2,11,0,4,1,0,0,48,38,1
98,48,3,171095,7,12,0,3,4,4,0,0,0,40,8,0
99,32,0,249409,11,9,4,7,3,2,1,0,0,40,38,0

In [22]:
y = train['target']
del train['target']
x = train

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [28]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=500,max_depth=6)
clf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, n_estimators=500)

In [37]:
from sklearn.metrics import accuracy_score
prediction = clf.predict(x_test)
acc =  accuracy_score(np.array(y_test),prediction)
print('accuracy:',acc*100)

accuracy:  85.90439144231755